#!/usr/bin/env bash
set -e

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
  echo "✓ .env already exists — skipping generation"
else
  echo "Generating .env with random secrets..."

  JWT_SECRET=$(openssl rand -hex 32)
  DB_PASSWORD=$(openssl rand -hex 16)

  cat > "$ENV_FILE" << EOF
# Auto-generated by init.sh — edit as needed

# Auth
JWT_SECRET=${JWT_SECRET}

# Server
PORT=3001
CORS_ORIGINS=http://localhost:3001

# MySQL
DB_HOST=mysql
DB_PORT=3306
DB_USER=root
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=supaproxy

# Redis
REDIS_HOST=redis
REDIS_PORT=6379

# Audit logs
SUPAPROXY_LOG_DIR=./var/logs
EOF

  echo "✓ .env created"
  echo ""
  echo "  JWT_SECRET: (auto-generated)"
  echo "  DB_PASSWORD: (auto-generated)"
fi

echo ""
echo "Starting SupaProxy..."
docker compose up --build -d

echo ""
echo "Waiting for services..."
sleep 5

echo ""
echo "✓ SupaProxy is running"
echo "  API:          http://localhost:3001"
echo "  Health check: http://localhost:3001/health"
echo ""
echo "Use the SDK or API to interact with SupaProxy."
echo "Docs: https://github.com/NumstackPtyLtd/supaproxy/wiki"
