#!/usr/bin/env bash
set -e

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
  echo "✓ .env already exists — skipping generation"
else
  echo "Generating .env with random secrets..."

  JWT_SECRET=$(openssl rand -hex 32)
  DB_PASSWORD=$(openssl rand -hex 16)

  cat > "$ENV_FILE" << EOF
# Auto-generated by init.sh — edit as needed

# Auth
JWT_SECRET=${JWT_SECRET}

# Server
PORT=3001
CORS_ORIGINS=http://localhost:4322,http://localhost:3001
DASHBOARD_URL=http://localhost:4322

# MySQL
DB_HOST=mysql
DB_PORT=3306
DB_USER=root
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=supaproxy

# Redis
REDIS_HOST=redis
REDIS_PORT=6379

# Audit logs
SUPAPROXY_LOG_DIR=./var/logs

# Default model for new workspaces (e.g. claude-sonnet-4-20250514, gpt-4o)
DEFAULT_MODEL=
EOF

  echo "✓ .env created"
  echo ""
  echo "  JWT_SECRET: (auto-generated)"
  echo "  DB_PASSWORD: (auto-generated)"
  echo ""
  echo ""
  read -rp "  Default model for new workspaces (e.g. gpt-4o, claude-sonnet-4-20250514) [gpt-4o]: " MODEL_INPUT
  DEFAULT_MODEL="${MODEL_INPUT:-gpt-4o}"
  sed -i.bak "s/^DEFAULT_MODEL=$/DEFAULT_MODEL=${DEFAULT_MODEL}/" "$ENV_FILE" && rm -f "${ENV_FILE}.bak"
  echo "  DEFAULT_MODEL: ${DEFAULT_MODEL}"
  echo ""
  echo "  → Add your AI API key in the dashboard after first login"
fi

echo ""
echo "Starting SupaProxy..."
docker compose up --build -d

echo ""
echo "Waiting for services..."
sleep 5

echo ""
echo "✓ SupaProxy is running"
echo "  Dashboard: http://localhost:4322"
echo "  API:       http://localhost:3001"
echo ""
echo "Visit http://localhost:4322/signup to create your organisation."
