#!/usr/bin/env bash
set -e

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
  echo "✓ .env already exists — skipping generation"
else
  echo "Generating .env with random secrets..."

  JWT_SECRET=$(openssl rand -hex 32)
  DB_PASSWORD=$(openssl rand -hex 16)

  cat > "$ENV_FILE" << EOF
# Auto-generated by init.sh — edit as needed
# This root .env is for docker-compose (service names, internal ports).
# For local dev (server on host), copy apps/server/.env.example to apps/server/.env
# and use 127.0.0.1 with mapped ports (3308/6380).

# Auth
JWT_SECRET=${JWT_SECRET}

# Server
PORT=3001
CORS_ORIGINS=http://localhost:3001

# MySQL
DB_HOST=mysql
DB_PORT=3306
DB_USER=root
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=supaproxy

# Redis
REDIS_HOST=redis
REDIS_PORT=6379

# Audit logs
SUPAPROXY_LOG_DIR=./var/logs
EOF

  # Also generate the local dev .env for apps/server
  LOCAL_ENV="apps/server/.env"
  cat > "$LOCAL_ENV" << EOF
# Auto-generated by init.sh — local dev (server on host, DB/Redis in Docker)

# Auth
JWT_SECRET=${JWT_SECRET}

# Server
PORT=3001
CORS_ORIGINS=http://localhost:4322,http://localhost:3001
DASHBOARD_URL=http://localhost:4322

# MySQL (Docker, mapped to host port 3308)
DB_HOST=127.0.0.1
DB_PORT=3308
DB_USER=root
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=supaproxy

# Redis (Docker, mapped to host port 6380)
REDIS_HOST=127.0.0.1
REDIS_PORT=6380

# Audit logs
SUPAPROXY_LOG_DIR=./var/logs
EOF

  echo "✓ .env created (root + apps/server)"
  echo ""
  echo "  JWT_SECRET:   (auto-generated)"
  echo "  DB_PASSWORD:  (auto-generated)"
fi

echo ""
echo "Starting SupaProxy..."
docker compose up --build -d

echo ""
echo "Waiting for services..."
sleep 5

echo ""
echo "✓ SupaProxy is running"
echo "  API:          http://localhost:3001"
echo "  Health check: http://localhost:3001/health"
echo ""
echo "Use the SDK or API to interact with SupaProxy."
echo "Docs: https://github.com/NumstackPtyLtd/supaproxy-server/wiki"
